# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT\DIABETES\diabetes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from call import predict
# from Classification import classfy
from Graphs import view
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt1
import sys
import csv


class prediction(object):

    def alertmsg(self, title, Message):
        self.warn = QtWidgets.QMessageBox()
        self.warn.setIcon(QtWidgets.QMessageBox.Information)
        self.warn.setWindowTitle(title)
        self.warn.setText(Message)
        self.warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.warn.setWindowIcon(QtGui.QIcon('error.png'))

        self.warn.exec_()

    def clear(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.output.clear()


    def pred(self):
        v = self.lineEdit.text()
        self.lineEdit.setValidator(QtGui.QIntValidator())   #age
        v1 = self.lineEdit_2.text()
        self.lineEdit_2.setValidator(QtGui.QIntValidator())  # glucose
        v2 = self.lineEdit_3.text()
        self.lineEdit_3.setValidator(QtGui.QIntValidator())   #bloodpressure
        v3 = self.lineEdit_4.text()
        self.lineEdit_4.setValidator(QtGui.QIntValidator())   #skinhthickness
        v4 = self.lineEdit_5.text()
        self.lineEdit_5.setValidator(QtGui.QIntValidator())     #insulin
        v5 = self.lineEdit_7.text()
        self.lineEdit_7.setValidator(QtGui.QIntValidator())      #bmi
        v6 = self.lineEdit_6.text()
        self.lineEdit_6.setValidator(QtGui.QIntValidator())      #diapedfunction


        fields = ('Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age')
        rows = [[v1,v2,v3,v4,v6,v5,v]]


        if v == '' or v == "null" or v1 == '' or v1 == "null" or v2 == '' or v2 == "null" or v3 == '' or v3 == "null" or v4 == '' or v4 == "null" or v5 == '' or v5 == "null" or v6 == '' or v6 == "null":
            self.alertmsg("error", "Please fill the All Details")

        else:
            with open('testdiabetes.csv', 'w', newline='') as f:
                write = csv.writer(f)
                write.writerow(fields)
                write.writerows(rows)

            result = predict("diabetes.csv", "testdiabetes.csv")
            self.output.setText(result)





        # print("Writing complete")
        # result = predict("diabetes.csv", "testdiabetes.csv")
        # print(result)



    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1090, 842)
        Dialog.setStyleSheet("QDialog{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));}\n"
"\n"
"")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1091, 80))
        self.frame.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 20, 1091, 51))
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(150, 180, 91, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(263, 177, 151, 31))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(199, 200, 176);")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(125, 250, 101, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(263, 245, 151, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(199, 200, 176);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(125, 302, 111, 71))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(263, 322, 151, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(199, 200, 176);")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(132, 403, 131, 71))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(263, 419, 151, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(199, 200, 176);")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(613, 202, 141, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(780, 200, 151, 31))
        self.lineEdit_5.setStyleSheet("background-color: rgb(199, 200, 176);")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(602, 345, 121, 81))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(780, 368, 151, 31))
        self.lineEdit_6.setStyleSheet("background-color: rgb(199, 200, 176);")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(660, 283, 51, 31))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(780, 279, 151, 31))
        self.lineEdit_7.setStyleSheet("background-color: rgb(199, 200, 176);")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(600, 500, 171, 61))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"color: rgb(240, 240, 240);\n"
"font: 12pt \"Algerian\";")
        self.pushButton.setObjectName("pushButton")


        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 500, 171, 61))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"color: rgb(240, 240, 240);\n"
"font: 12pt \"Algerian\";")
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(400, 660, 131, 41))
        self.label_9.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 75 26pt \"Arial Narrow\";\n"
"font: 75 24pt \"Agency FB\";")
        self.label_9.setObjectName("label_9")
        self.output = QtWidgets.QLabel(Dialog)
        self.output.setGeometry(QtCore.QRect(530, 630, 301, 111))
        self.output.setStyleSheet("background-color: rgb(200, 200, 113);\n"
"color: rgb(255, 0, 0);\n"
"font: 24pt \"Algerian\";")
        self.output.setText("")
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setObjectName("output")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton_2.clicked.connect(self.clear)
        self.pushButton.clicked.connect(self.pred)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; color:#c82519;\">DIABETES PREDICTOR</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">AGE</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">GLUCOSE</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">BLOOD</span></p><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">PRESSURE</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">SKIN</span></p><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">THICKNESS</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">INSULIN</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">DIABETES<br/>PEDIGREE<br/>FUNCTION</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">BMI</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "PREDICT"))
        self.pushButton_2.setText(_translate("Dialog", "RESET"))

        self.label_9.setText(_translate("Dialog", "RESULT   :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = prediction()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
